### ISSUE TITLE
Configuration without singletons for multiple merchant support

### ISSUE THREAD

**Issue by SimonBackx** [paynl/nodejs-sdk#11]
Because of the singletons in the code, it is impossible to use the library if you need to process payments for multiple submerchants. Would it be possible to add some kind of class based configurations instead of singletons?

**Comment by woutse** [comment]
Thanks for your message. Maybe. We'll have to look into this, but this might take a while. You are of course free to make changes yourself and you can add a pullrequest if you'd like.
