### ISSUE TITLE
Error is checked before parsing the JSON response

### ISSUE THREAD

**Issue by SimonBackx** [paynl/nodejs-sdk#12]
The isError method will always return false since the JSON is not yet parsed.

`body["status"]` etc. will always return undefined.

https://github.com/paynl/nodejs-sdk/blob/7f9124926dbef786326b6c1632aede01b0168279/src/api/api.ts#L53

**Comment by woutse** [comment]
Thanks for your message. We'll investigate this and try to fix this a.s.a.p!

**Comment by woutse** [comment]
We made a change which solves this problem. Thanks again for your message.
