### ISSUE TITLE
Invalid reference throws also 'invalid secret' 

### ISSUE THREAD

**Issue by nvanoost** [paynl/nodejs-sdk#14]
Just discovered that the 'invalid secret' error is also thrown when generating an UUID with an invalid reference (for example longer that 8 chars or with invalid chars).
It was taking some time from me to discover that it was not the secret but the reference that was invalid.

**Comment by woutse** [comment]
Thanks for your message. I was not able to reproduce this. Perhaps you can provice us some sampledate to do this?
