### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sashaskr** [paynl/nodejs-sdk#2]
Hello. At the section [https://github.com/paynl/nodejs-sdk#starting-a-transaction](https://github.com/paynl/nodejs-sdk#starting-a-transaction) link to the all supported options is pointing to 404 

> This example shows the minimum required attributes to start a transaction. The full version with all supported options is located [here](https://github.com/paynl/nodejs-sdk/blob/master/build/samples/transaction/start.js)

**Comment by andypieters** [comment]
Ah... yes
I removed the javascript sources from the github repository, but i forgot about the samples.
The samples are there in typescript, can you work with that?
https://github.com/paynl/nodejs-sdk/blob/master/src/samples/transaction/start.ts

**Comment by andypieters** [comment]
Also, if you need the samples in javascript, they are generated in your local node_modules directory.
The path is: node_modules/paynl-sdk/lib/samples
